// <auto-generated />
namespace PideYa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cantidadininsumochangedtodecimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cantidadininsumochangedtodecimal));
        
        string IMigrationMetadata.Id
        {
            get { return "201905302144486_cantidad in insumo changed to decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
