// <auto-generated />
namespace PideYa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class proveedorinsumorecetatablesadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(proveedorinsumorecetatablesadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201905301916461_proveedor insumo receta tables added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
